---
title: "word_frequency"
author: "Quan Dang"
date: "2024-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r simple, include=FALSE}
# reading in the frequencies txt file from the Stylo package, UTF-8 encoding needed for Cyrillic
wordFreq <- read.table("table_with_frequencies.txt", sep=" ", header=T, encoding="UTF-8")

# turning the index into a column
wordFreq <- cbind(wordName = rownames(wordFreq), wordFreq)
rownames(wordFreq) <- 1:nrow(wordFreq)

# simple charts of each text with 20 most common words
par(mfrow=c(2,3))
barplot(wordFreq[1:20, 2], name=wordFreq[1:20, 1],
        main="Translation 1", xlab="Word", ylab="Percentage of text")
barplot(wordFreq[1:20, 3], name=wordFreq[1:20, 1],
        main="Translation 2", xlab="Word", ylab="Percentage of text")
barplot(wordFreq[1:20, 4], name=wordFreq[1:20, 1],
        main="Translation 3", xlab="Word", ylab="Percentage of text")
barplot(wordFreq[1:20, 5], name=wordFreq[1:20, 1],
        main="Translation 4", xlab="Word", ylab="Percentage of text")
barplot(wordFreq[1:20, 6], name=wordFreq[1:20, 1],
        main="Translation 5", xlab="Word", ylab="Percentage of text")

# the collective percentage of most used 5000 words according to stylo
sum(wordFreq$braude_twain)
sum(wordFreq$chukovsky_twain)
sum(wordFreq$daruzes_twain)
sum(wordFreq$engel.gardt_twain)
sum(wordFreq$unknown_twain)
```
## percentage of 5000 most common words in translations:
### Braude Translation:
86.09046%

### Chukovsky Translation:
85.00925%

### Daruzes Translation:
86.52966%

### Engel Gardt Translation:
80.74109%

### Unknown Translation:
85.46636%


```{r exploration, include=FALSE}

```